### ISSUE TITLE
Failing while parse phone numbers.

### ISSUE THREAD

**Issue by lerdem** [digitalashes/olx-parser#4]
I suppose you expecting json here
```python
 response.json().get('value')
```
but parser retrieved html here. I dont get why.

```
 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    main()
  File "main.py", line 20, in main
    new_ads = filter_new_ads(session, ads)
  File "~/olx-parser/olx/__init__.py", line 101, in filter_new_ads
    result.append(fetch_ads_detail(session, ad))
  File "~/olx-parser/olx/__init__.py", line 183, in fetch_ads_detail
    phone_numbers = response.json().get('value')
  File "~/.local/share/virtualenvs/olx-parser-rqlDcgFl/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any ideas?

**Comment by rkuksenko** [comment]
From 09.2019 OLX become blocks suspicious users, so, this method doesn't work
